If you navigate for tornados in a specific state on the NOAA site https://www.ncei.noaa.gov/, you will get a url like this pattern

In [1]:
import pandas as pd

url = r"https://www.ncei.noaa.gov/stormevents/csv?eventType=%28C%29+Tornado&beginDate_mm=05&beginDate_dd=01&beginDate_yyyy=2024&endDate_mm=05&endDate_dd=31&endDate_yyyy=2025&county=ALL&hailfilter=0.00&tornfilter=0&windfilter=000&sort=DT&submitbutton=Search&statefips=48%2CTEXAS"
df = pd.read_csv(url, dtype={"BEGIN_TIME" : str, "END_TIME" : str})

df

,EVENT_ID,CZ_NAME_STR,BEGIN_LOCATION,BEGIN_DATE,BEGIN_TIME,EVENT_TYPE,MAGNITUDE,TOR_F_SCALE,DEATHS_DIRECT,INJURIES_DIRECT,...,END_LOCATION,END_DATE,END_TIME,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EVENT_NARRATIVE,EPISODE_NARRATIVE,ABSOLUTE_ROWNUMBER
0,1175479,DONLEY CO.,CLARENDON,05/01/2024,1456,Tornado,,EF0,0,0,...,CLARENDON,05/01/2024,1458,34.9165,-100.9991,34.9152,-100.9927,This tornado touched down briefly in ranch lan...,An elongated upper level trough promoted a dry...,1
1,1175480,DONLEY CO.,ASHTOLA,05/01/2024,1504,Tornado,,EF1,0,0,...,CLARENDON,05/01/2024,1519,34.9207,-101.0125,34.9165,-100.9815,This tornado touched down after the initial pa...,An elongated upper level trough promoted a dry...,2
2,1175474,HUTCHINSON CO.,PRINGLE,05/01/2024,1614,Tornado,,EFU,0,0,...,PRINGLE,05/01/2024,1616,36.0183,-101.1136,36.0107,-101.0982,This tornado briefly touched down in the Canad...,An elongated upper level trough promoted a dry...,3
3,1166279,HALL CO.,TURKEY,05/01/2024,1649,Tornado,,EFU,0,0,...,TURKEY,05/01/2024,1649,34.4927,-100.9354,34.4927,-100.9354,Several storm chasers photographed a brief tor...,Numerous severe thunderstorms developed on the...,4
4,1175475,HANSFORD CO.,SPEARMAN,05/01/2024,1743,Tornado,,EF0,0,0,...,SPEARMAN,05/01/2024,1744,36.1894,-101.2097,36.1848,-101.2089,This tornado touched down to the west of Count...,An elongated upper level trough promoted a dry...,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,1267458,MENARD CO.,MENARD,05/26/2025,1513,Tornado,,EFU,0,0,...,MENARD,05/26/2025,1516,30.8900,-99.8000,30.8750,-99.7853,A trained spotter reported a tornado just sout...,The combination of an upper level area of low ...,204
204,1265149,CARSON CO.,WHITE DEER,05/26/2025,1733,Tornado,,EFU,0,0,...,WHITE DEER,05/26/2025,1735,35.3600,-101.1600,35.3600,-101.1600,Several photos and videos were submitted of a ...,During the afternoon of the 26th several isola...,205
205,1260975,DAWSON CO.,PUNKIN CENTER,05/29/2025,1709,Tornado,,EF1,0,0,...,LAMESA JOHNSON ARPT,05/29/2025,1724,32.8362,-102.0815,32.7700,-102.0000,A dusty tornado was reported west of Highway 1...,A disturbance in the quasi-zonal/northwesterly...,206
206,1260976,DAWSON CO.,SPARENBURG,05/29/2025,1746,Tornado,,EF1,0,0,...,SPARENBURG,05/29/2025,1750,32.6500,-101.8800,32.6000,-101.8500,This was the estimated path of a brief tornado...,A disturbance in the quasi-zonal/northwesterly...,207
207,1267460,COLEMAN CO.,GLEN COVE,05/29/2025,2031,Tornado,,EFU,0,0,...,GLEN COVE,05/29/2025,2037,31.8600,-99.6700,31.8617,-99.6540,A storm chaser posted a video on social media ...,The combination of an upper level area of low ...,208

See if we can have AI modify this code so it figures out the URL's for all 50 states, and we can download them all into a single dataframe. Don't be surprised if we have to do a little debugging and troubleshooting!

In [ ]:
# put code here

Verify the data by seeing how many states and the count of records occur in each one.

In [ ]:
# put code here

Now let's see if we can get greedy. NOAA will cut off datasets at 500 records so we cannot use too large of date ranges for a given state. But what if we queried one date at a time for every state?

Successfully downloaded data for KANSAS on 2024-05-01
Successfully downloaded data for LOUISIANA on 2024-05-02
Successfully downloaded data for MISSOURI on 2024-05-02
Successfully downloaded data for OKLAHOMA on 2024-05-01
Successfully downloaded data for TEXAS on 2024-05-01
Successfully downloaded data for TEXAS on 2024-05-02
Successfully downloaded data for WASHINGTON on 2024-05-01

,EVENT_ID,CZ_NAME_STR,BEGIN_LOCATION,BEGIN_DATE,BEGIN_TIME,EVENT_TYPE,MAGNITUDE,TOR_F_SCALE,DEATHS_DIRECT,INJURIES_DIRECT,...,END_LOCATION,END_DATE,END_TIME,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EVENT_NARRATIVE,EPISODE_NARRATIVE,ABSOLUTE_ROWNUMBER
0,1176393,GOVE CO.,GOVE,05/01/2024,1726,Tornado,,EFU,0,0,...,GOVE,05/01/2024,1727,38.7497,-100.4661,38.7500,-100.4648,Multiple storm chasers reported an EF-U landsp...,Two rounds of severe weather impacted Northwes...,1
1,1176512,GOVE CO.,GOVE,05/01/2024,1955,Tornado,,EFU,0,0,...,GOVE,05/01/2024,1956,38.6990,-100.3057,38.6987,-100.3055,Multiple reports from media and storm chasers ...,Two rounds of severe weather impacted Northwes...,2
2,1213042,LANE CO.,PENDENNIS,05/01/2024,1956,Tornado,,EFU,0,0,...,PENDENNIS,05/01/2024,2001,38.7000,-100.3100,38.6900,-100.3000,At roughly this point the tornado may have mov...,Hail and landspouts 05/01.,3
3,1185126,SABINE PAR.,FT JESSUP,05/02/2024,909,Tornado,,EF1,0,0,...,FT JESSUP,05/02/2024,919,31.6682,-93.4195,31.6965,-93.3378,A weak EF-1 tornado with estimated maximum win...,A mesoscale convective vortex (MCV) provided s...,1
4,1182535,JEFFERSON DAVIS PAR.,WELSH ARPT,05/02/2024,1032,Tornado,,EFU,0,0,...,WELSH ARPT,05/02/2024,1032,30.2065,-92.8326,30.2065,-92.8326,A brief tornado touched down in an empty field...,A series of upper disturbance moved across the...,2
5,1167379,JASPER CO.,(JLN)JOPLIN MUNI ARP,05/02/2024,1240,Tornado,,EF1,0,0,...,(JLN)JOPLIN MUNI ARP,05/02/2024,1242,37.1546,-94.5204,37.1600,-94.5100,NWS survey confirmed an EF-1 tornado with maxi...,"Storms developed along a cold front, with rota...",1
6,1184070,COMANCHE CO.,FAXON,05/01/2024,2304,Tornado,,EFU,0,0,...,FAXON,05/01/2024,2304,34.4580,-98.6010,34.4580,-98.6010,A Tornado Debris Signature (TDS) was observed ...,Broad upper troughing/southwesterly flow exten...,1
7,1175479,DONLEY CO.,CLARENDON,05/01/2024,1456,Tornado,,EF0,0,0,...,CLARENDON,05/01/2024,1458,34.9165,-100.9991,34.9152,-100.9927,This tornado touched down briefly in ranch lan...,An elongated upper level trough promoted a dry...,1
8,1175480,DONLEY CO.,ASHTOLA,05/01/2024,1504,Tornado,,EF1,0,0,...,CLARENDON,05/01/2024,1519,34.9207,-101.0125,34.9165,-100.9815,This tornado touched down after the initial pa...,An elongated upper level trough promoted a dry...,2
9,1175474,HUTCHINSON CO.,PRINGLE,05/01/2024,1614,Tornado,,EFU,0,0,...,PRINGLE,05/01/2024,1616,36.0183,-101.1136,36.0107,-101.0982,This tornado briefly touched down in the Canad...,An elongated upper level trough promoted a dry...,3
10,1166279,HALL CO.,TURKEY,05/01/2024,1649,Tornado,,EFU,0,0,...,TURKEY,05/01/2024,1649,34.4927,-100.9354,34.4927,-100.9354,Several storm chasers photographed a brief tor...,Numerous severe thunderstorms developed on the...,4
11,1175475,HANSFORD CO.,SPEARMAN,05/01/2024,1743,Tornado,,EF0,0,0,...,SPEARMAN,05/01/2024,1744,36.1894,-101.2097,36.1848,-101.2089,This tornado touched down to the west of Count...,An elongated upper level trough promoted a dry...,5
12,1175476,HANSFORD CO.,SPEARMAN,05/01/2024,1746,Tornado,,EF0,0,0,...,SPEARMAN,05/01/2024,1748,36.1851,-101.1895,36.1846,-101.1856,"A small, weak tornado moved east across the Sp...",An elongated upper level trough promoted a dry...,6
13,1175477,HANSFORD CO.,SPEARMAN,05/01/2024,1753,Tornado,,EF1,0,0,...,SPEARMAN,05/01/2024,1755,36.1978,-101.1874,36.2140,-101.1757,This tornado occurred on the northeast side of...,An elongated upper level trough promoted a dry...,7
14,1166282,CROSBY CO.,LORENZO,05/01/2024,1810,Tornado,,EFU,0,0,...,LORENZO,05/01/2024,1810,33.7568,-101.5300,33.7568,-101.5300,Local broadcast media relayed a photograph of ...,Numerous severe thunderstorms developed on the...,8
15,1166288,HALL CO.,TURKEY,05/01/2024,1852,Tornado,,EFU,0,0,...,TURKEY,05/01/2024,1857,34.4146,-100.8303,34.4309,-100.8190,Numerous storm chasers photographed a tornado ...,Numerous severe thunderstorms developed on the...,9
16,1187523,RUNNELS CO.,BALLINGER,05/02/2024,1653,Tornado,,EF2,0,0,...,BENOIT,05/02/2024,1715,31.7582,-99.9230,31.7121,-99.8689,The tornado damaged trees off County Road 121 ...,A favorable weather pattern for widespread sev...,1
17,1220761,JONES CO.,BOYDS CHAPEL,05/02/2024,1729,Tornado,,EFU,0,0,...,BOYDS CHAPEL,05/02/2024,1737,32.7767,-100.0502,32.7662,-100.0463,Spotter reported a tornado briefly touched dow...,A favorable weather pattern for widespread sev...,2
18,1187524,CONCHO CO.,CONCHO,05/02/2024,1739,Tornado,,EF2,0,0,...,MILLERSVIEW,05/02/2024,1804,31.4831,-99.6676,31.4188,-99.5993,The tornado damaged electrical transmission li...,A favorable weather pattern for widespread sev...,3
19,1187506,JONES CO.,HAWLEY,05/02/2024,1806,Tornado,,EF3,0,4,...,HAWLEY,05/02/2024,1833,32.6241,-99.8609,32.5873,-99.8339,The tornado was part of a cyclical supercell m...,A favorable weather pattern for widespread sev...,4
20,1187547,KITTITAS CO.,VANTAGE,05/01/2024,1330,Tornado,,EF0,0,0,...,VANTAGE,05/01/2024,1340,47.0693,-120.0547,47.0743,-120.0543,"A video taken from George, WA showed a landspo...",A marginally unstable atmosphere and breezy wi...,1

After that, put the data into a SQLite database.